[build]
  base = "frontend"      # Netlify will only look inside frontend for build
  publish = "frontend/"          # Publish files from frontend folder
  command = ""           # No build command for static frontend
